# Generated by Django 2.0.4 on 2018-04-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_year',
            field=models.IntegerField(verbose_name='Model Year'),
        ),
    ]
