# Generated by Django 2.0.4 on 2018-04-16 18:15

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20180415_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='cars'),
        ),
    ]
