# Generated by Django 2.0.4 on 2018-04-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20180416_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_picked',
            field=models.BooleanField(default=True),
        ),
    ]
