# Generated by Django 2.0.4 on 2018-04-19 23:02

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_car_picked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='dealer_zip',
        ),
        migrations.AddField(
            model_name='car',
            name='car_decription',
            field=models.CharField(default='Good Car!', max_length=200, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='car',
            name='dealer_area',
            field=models.CharField(choices=[('Troy', 'Troy'), ('Albany', 'Albany')], default='Troy', max_length=200, verbose_name='Dealer Area'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='cars/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_make',
            field=models.CharField(choices=[('Honda', 'Honda'), ('Mazda', 'Mazda'), ('Subaru', 'Subaru')], max_length=200, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(choices=[('BRZ', 'BRZ'), ('Miata RF', 'Miata RF'), ('Civic Sport', 'Civic Sport'), ('Impreza Sport', 'Impreza Sport'), ('Accord Touring', 'Accord Touring')], max_length=200, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_picked',
            field=models.BooleanField(default=False, verbose_name='Is Picked'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_web',
            field=models.URLField(verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='car',
            name='dealer_name',
            field=models.CharField(choices=[('Rensselaer Honda', 'Rensselaer Honda'), ('Carbone Subaru', 'Carbone Subaru'), ('Cooley Mazda', 'Cooley Mazda')], max_length=200, verbose_name='Dealership'),
        ),
        migrations.AlterField(
            model_name='car',
            name='dealer_web',
            field=models.URLField(verbose_name='Dealer Website'),
        ),
    ]
