# Generated by Django 2.0.4 on 2018-04-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20180419_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_decription',
            new_name='car_description',
        ),
    ]
