# Generated by Django 2.0.4 on 2018-04-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20180419_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_reliability',
            field=models.IntegerField(default=5, verbose_name='Reliability'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_make',
            field=models.CharField(choices=[('Honda', 'Honda'), ('Mazda', 'Mazda'), ('Subaru', 'Subaru'), ('Dodge', 'Dodge'), ('Volvo', 'Volvo'), ('Hyundai', 'Hyundai'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Toyota', 'Toyota')], max_length=200, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(choices=[('BRZ', 'BRZ'), ('Miata RF', 'Miata RF'), ('Civic Sport', 'Civic Sport'), ('Impreza Sport', 'Impreza Sport'), ('Accord Touring', 'Accord Touring'), ('Ram Pickup', 'Ram Pickup'), ('Accent GLS', 'Accent GLS'), ('Malibu LT', 'Malibu LT'), ('Colorado LT', 'Colorado LT'), ('Edge SEL', 'Edge SEL'), ('CR-V EX-L', 'CR-V EX-L'), ('Fusion SE', 'Fusion SE'), ('RAV4 Base I4 4WD', 'RAV4 Base I4 4WD'), ('Tucson GLS', 'Tucson GLS'), ('Focus SE', 'Focus SE'), ('Pilot EX-L', 'Pilot EX-L'), ('Focus SE Sedan', 'Focus SE Sedan'), ('Outback Premium', 'Outback Premium')], max_length=200, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='dealer_area',
            field=models.CharField(choices=[('Troy', 'Troy'), ('Latham', 'Latham')], default='Troy', max_length=200, verbose_name='Dealer Area'),
        ),
        migrations.AlterField(
            model_name='car',
            name='dealer_name',
            field=models.CharField(choices=[('Rensselaer Honda', 'Rensselaer Honda'), ('Carbone Subaru', 'Carbone Subaru'), ('Cooley Mazda', 'Cooley Mazda'), ('D & G Auto Sales & Service', 'D & G Auto Sales & Service'), ("J&J's Auto Sales", "J&J's Auto Sales"), ('Goldstein Chrysler Jeep Dodge Ram', 'Goldstein Chrysler Jeep Dodge Ram'), ('Northeast Acura', 'Northeast Acura')], max_length=200, verbose_name='Dealership'),
        ),
    ]
